### ISSUE TITLE
Unable to fetch dev key

### ISSUE THREAD

**Issue by xd003** [pvpscript/pastemngr#1]
```pastemngr --fetch-dev-key```
After running the above command , it asks for username and password . I am entering it correctly but it always outputs the error - Unable to fetch dev key

**Comment by xd003** [comment]
I added my api_key manually and it worked but still this issue could be solved ideally so keeping it open

**Comment by pvpscript** [comment]
Hello,
I'm sorry for the very late response.

Regarding the `--fetch-dev-key` argument, it is very unreliable, as stated on the `README` text, since it's not official to the `pastebin.com` API. This is very likely happening because the process for fetching the key automatically, relies on html parsing and sometimes the page can prompt a recaptcha system, which cannot be circumvented.

The best solution to this, at the moment, is to simply fetch the key manually from their site.
